services:
  # 1. EUREKA
  - type: web
    name: eureka-server
    env: docker
    dockerContext: .
    dockerfilePath: rental-vehicle/Dockerfile
    plan: free

  # 2. VEHICLE SERVICE
  - type: web
    name: vehicle-service
    env: docker
    dockerContext: .
    dockerfilePath: vehicle/Dockerfile
    plan: free
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://eureka-server:8761/eureka
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: vehicle-db
          property: connectionString

  # 3. OPERATION SERVICE
  - type: web
    name: operation-service
    env: docker
    dockerContext: .
    dockerfilePath: operation/Dockerfile
    plan: free
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://eureka-server:8761/eureka
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: operation-db
          property: connectionString

  # 4. GATEWAY
  - type: web
    name: gateway-service
    env: docker
    dockerContext: .
    dockerfilePath: gateway/Dockerfile
    plan: free
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://eureka-server:8761/eureka

# 5. BASES DE DATOS (POSTGRES NATIVO DE RENDER)
databases:
  - name: vehicle-db
    databaseName: vehicle_db
    plan: free
  - name: operation-db
    databaseName: operation_db
    plan: free